### ISSUE TITLE
Point Cloud Representation

### ISSUE THREAD

**Issue by jaidevshriram** [lukasHoel/text2room#10]
Hey, love this work! I was wondering why you preferred a mesh representation over point clouds - why not just create the mesh after the entire generation process is done?

**Comment by Caoang327** [comment]
Thanks for your interest! We tried point cloud representation initially and found it led to more severe distortions and ill-structured inpainting masks. 

Point Cloud is a more discrete representation compared to mesh, and even rendering a flat region/plane represented by a point cloud from an extreme viewpoint may lead to many missing regions inside this plane, while mesh could solve this problem appropriately
