### ISSUE TITLE
Can't find text2room/checkpoints

### ISSUE THREAD

**Issue by scooter7** [lukasHoel/text2room#16]
Hi,

I'm trying to move irondepth_scannet.pt and normal_scannet.pt into folder: text2room/checkpoints but don't see that directory in the text2room directory.

Thanks!

**Comment by lukasHoel** [comment]
Hi, please create the directory manually :)

**Comment by scooter7** [comment]
Hi again,

Now, I'm getting error:

ERROR: No matching distribution found for nvidia-cudnn-cu11==8.5.0.96

Thanks!

**Comment by lukasHoel** [comment]
You can try to relax the versions in the requirements.txt file and install any (the latest) version of the respective packages yourself.

**Comment by lukasHoel** [comment]
Let me know if you have further questions about installation.
