### ISSUE TITLE
codes doesn't run successfully when computed normals

### ISSUE THREAD

**Issue by hey0chen** [lukasHoel/text2room#17]
loaded output/living_room/full_trajectory/a_living_room_with_a_lit_furnace,_couch_/no_input_image_file/2023-05-22_20:05:49.520666Z/fused_mesh/after_generation.ply
computed normals

I think this problem maybe caused by pymeshlab
![img_v2_ce29e4f2-203d-468d-8158-3a4a10449f8g](https://github.com/lukasHoel/text2room/assets/118654642/c2d0f0b3-0733-435d-8520-6b33396ce4c0)

**Comment by lukasHoel** [comment]
What's the error that you get? You can try to run this step in the GUI of Meshlab manually.

**Comment by hey0chen** [comment]
> What's the error that you get? You can try to run this step in the GUI of Meshlab manually.

The code doesn't seem to run anymore 
![image](https://github.com/lukasHoel/text2room/assets/118654642/0c07634a-5cc9-420f-b970-f6f5a2c1d517)

and I get the following error when I use meshlab manually
![bLfV5uJWIT](https://github.com/lukasHoel/text2room/assets/118654642/3d216115-d202-49b7-8129-24ccbd344dc2)

**Comment by lukasHoel** [comment]
- You need to compute the normals manually in Meshlab as well before running the Poisson step

- For me, poisson surface reconstruction usually finishes in ~10 minutes. Maybe #5 is also related, could you check if it is a similar issue by trying with the GUI on your local machine?

**Comment by hey0chen** [comment]
> 

Thanks for your answer, I successfully manually running Poisson step with the GUI on mt local mechine, it seems to be the machine's problem, I will check it

**Comment by zf-666** [comment]
I meet the same problem, have u solve it?  Thank u

**Comment by hey0chen** [comment]
> 
There seems to be a problem in this part of the code
`    ms.generate_surface_reconstruction_screened_poisson(depth=depth)
`
The parameter "depth" affects the speed,I changed depth=6 and tried many times, only one worked but it was still very slow.

**Comment by zf-666** [comment]
I found this step to run on my A100 server for 34163s, nearly 10 hours, but yes it does work.

**Comment by lukasHoel** [comment]
> I found this step to run on my A100 server for 34163s, nearly 10 hours, but yes it does work.

That is definitely way too long for meshes with about 3M vertices. Double check if all CPUs are used and maybe try different versions of pymeshlab or an alternative implementation (e.g. Open3D).
