### ISSUE TITLE
Terms meanings in trajectory json files

### ISSUE THREAD

**Issue by Jihyun0510** [lukasHoel/text2room#19]
I really appreciate your amazing work and the codes that you provided.

I have encountered some terms that are not mentioned in the paper so I want to clarify them.

1. **negative_prompt**
2. **surface_normal_threshold**
3. **single color for text_prompt**: I thought the same text prompt execept for the floor and the ceiling would be used for each came pose.

Thank you for your help!

**Comment by Jihyun0510** [comment]
Problem solved for negative_prompt and surface_normal threshold! 
In addition, I want to ask what is bbox in the codes!

Thank you so much!

**Comment by lukasHoel** [comment]
We found it is helpful to use "single color" as prompt for completion. If only a few pixels need to be inpainted, we do not want to create another object.

Bbox is the bounding box of the generated mesh.

**Comment by Jihyun0510** [comment]
Thank you so much for your quick reponse.

Why would you need a bounding box for the generated mesh?

**Comment by lukasHoel** [comment]
We use it during completion to constrain where the additional camera poses can be placed.

**Comment by Jihyun0510** [comment]
Thank you so much for your kind answers!
