### ISSUE TITLE
Codes running on CPU

### ISSUE THREAD

**Issue by Jihyun0510** [lukasHoel/text2room#20]
Thanks for your great work again

While running the codes, I found out that at first the codes run on GPU then after some time they start to run on CPU.

Could you explain why is that and was it intended?

Thanks!

**Comment by lukasHoel** [comment]
Hi, I think the only parts that run on the CPU are poisson surface reconstruction and clean-up steps with Open3D/trimesh. That is because these things do not have a GPU implementation as far as I'm aware. Everything else should be on the GPU though. Is it not the case?

**Comment by Jihyun0510** [comment]
Yes, within a minute GPU usage starts from around 16000mb and drops to approximately 8000mb. From that time CPU usage amount surges. Could there be any other reason?

thanks for your reply

**Comment by lukasHoel** [comment]
Could you try to debug which tensors are not stored on the GPU?

**Comment by Jihyun0510** [comment]
Like you have mentioned, it was the code "ms.generate_surface_reconstruction_screened_poisson(depth=depth)" which cuased the overusage of CPU. Is there any other alternative way to run this code and replicate your results? Becuase our computing system cannot afford such CPU usage amount.

**Comment by lukasHoel** [comment]
> Becuase our computing system cannot afford such CPU usage amount.

You can always try to run the poisson surface reconstruction in the meshlab GUI, e.g. also see #17
