### ISSUE TITLE
Results got worse after quadratic decimation and poisson

### ISSUE THREAD

**Issue by Jihyun0510** [lukasHoel/text2room#21]
I always appreciate your kind answers and your great work

Running the codes (generate_scene.py) with the default setting, I found out that results get worse as time passes.

Here are the results for the living_room.json:

**Fused frame until 200**
![image](https://github.com/lukasHoel/text2room/assets/78332579/11f96b75-80db-4d1c-9fdf-5c72f8c14c13)

**Fused final**
![image](https://github.com/lukasHoel/text2room/assets/78332579/8a3da5ec-7be4-41e7-8aa8-b2c341d610f7)

**After poisson**
![image](https://github.com/lukasHoel/text2room/assets/78332579/5415b295-9e9e-4ad4-bf4d-ae21bdaf6b5b)

**After qudratic decimation*
![image](https://github.com/lukasHoel/text2room/assets/78332579/95bad609-db1c-45c6-ae1a-8c0c1589e9d9)

Could you explain the reasons? What should I do to get the best results like in your paper?

**Comment by lukasHoel** [comment]
Hi you can take a look at the discussion in #13 and try out those steps. If the ceiling looks like this after the first stage, the default parameters for completion are unable to inpaint it properly. That is, our camera sampling fills in some holes, but others remain. As a result, poisson surface reconstruction will create these smoothing artifacts to make the mesh watertight. Also see Fig9. in the paper for a discussion about this failure mode of the method.

The two solutions are:

- fiddle with hparams for completion as discussed in #13 (or improve camera sampling all together to inpaint all holes).

- only complete meshes who's ceilings are not degenerate like here

**Comment by lukasHoel** [comment]
Hi you can take a look at the discussion in #13 and try out those steps. If the ceiling looks like this after the first stage, the default parameters for completion are unable to inpaint it properly. That is, our camera sampling fills in some holes, but others remain. As a result, poisson surface reconstruction will create these smoothing artifacts to make the mesh watertight. Also der Fig9. in the paper for a discussion about this failure mode of the method.

The two solutions are:

- fiddle with hparams for completion as discussed in #13 (or improve camera sampling all together to inpaint all holes).

- only complete meshes who's ceilings are not degenerate like here

**Comment by Jihyun0510** [comment]
Thank you! I will try that
