### ISSUE TITLE
Skipping stage 1 and utilizing an existing point cloud

### ISSUE THREAD

**Issue by Jihyun0510** [lukasHoel/text2room#24]
Thanks for your kind responses

I am trying to use an existing point cloud, and utilize only your stage 2 codes to turn it into a mesh and close holes. 

However, looking at your codes, it seems like rather than a  point cloud, mesh components(vertices, faces, vertices colors) are required.

Is there any way to load a point cloud in the middle of the codes before stage2 (completion stage)???

**Comment by lukasHoel** [comment]
You are correct, stage 2 requires a mesh already. We continuously triangulate the mesh from each new image in stage 1.
