### ISSUE TITLE
Use poor gpu to run

### ISSUE THREAD

**Issue by Jacky-MYQ** [lukasHoel/text2room#27]
What a excellent project! How can i use a poor gpu to run? Which parameters should i change?

**Comment by lukasHoel** [comment]
You can try the things mentioned here: https://github.com/lukasHoel/text2room/issues/2

**Comment by Jacky-MYQ** [comment]
> You can try the things mentioned here: #2

Thank you for taking time out of your busy schedule to reply to my message
