### ISSUE TITLE
I use Blender to show .ply files, but i can't see any textures of the room.

### ISSUE THREAD

**Issue by Jacky-MYQ** [lukasHoel/text2room#28]
Hi,
With the help of you , i successfully run `python generate_scene.py ` that i'm very grateful to your help.
But when i got the outputs, i use Blender to open .ply files, i just got a room with a gray geometry that without any textures.
I want to make sure if i use the wrong tool to open .ply files.
Thanks a million！！！

**Comment by lukasHoel** [comment]
Per default, blender uses geometry shading to render a mesh file. You would have to add a vertex color shader to blender.
Alternatively, you can open the .ply file in Meshlab.

**Comment by Jacky-MYQ** [comment]
Thanks a lot! I can see the textures when i use MeshLab!
