### ISSUE TITLE
Visualization without roof.

### ISSUE THREAD

**Issue by Sharpiless** [lukasHoel/text2room#30]
Hi, thanks for your excellent work! Could you release the visualization code of the textured meshes without a roof, as in Figure 1 and Figure 5? Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by lukasHoel** [comment]
Hi, there is no code, I did it manually with meshlab. First align the mesh with the XY plane and then choose some height at which to cut

**Comment by Sharpiless** [comment]
I see. Thank you very much!
