### ISSUE TITLE
convert to video

### ISSUE THREAD

**Issue by kitty384** [lukasHoel/text2room#32]
How can I render the video in the project page?

**Comment by lukasHoel** [comment]
You can load the mesh in blender, define a custom camera path and then
render images along that.

kitty384 ***@***.***> schrieb am Mi., 28. Feb. 2024, 15:42:

**Comment by kitty384** [comment]
But when I open the .ply file with blender, it is gray and the surface has no color. How should I render it?

**Comment by lukasHoel** [comment]
There are a bunch of tutorials on YouTube about this. You want to render
the vertex colors without any shading. That needs to be configured manually
in blender.

kitty384 ***@***.***> schrieb am Sa., 2. März 2024, 09:16:
