### ISSUE TITLE
where to put the optional pretrained weights?

### ISSUE THREAD

**Issue by manxw** [lukasHoel/text2room#33]
Hi.. thanks for this repo.. Just a one question. where to put the optional pretrained weights.

**(Optional) Download the pretrained model weights for the text-to-image model:**

Whenever I tried to run this, I get cuda out of memory error; so I thought to start with pretrainned weights,

**torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.16 GiB (GPU 0; 10.75 GiB total capacity; 8.88 GiB already allocated; 1.54 GiB free; 8.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**

**Comment by lukasHoel** [comment]
> where to put the optional pretrained weights.

You can put them anywhere you want, and then you have to create a symbolic link to the `checkpoints` directory:

```
ln -s <path/to/stable-diffusion-2-inpainting> checkpoints
ln -s <path/to/stable-diffusion-2-1> checkpoints
```

> Whenever I tried to run this, I get cuda out of memory error

The OOM error will not be solved when downloading weights to your local file system. Rather you want to try tricks mentioned here to reduce the memory consumption on a small GPU: #2
