### ISSUE TITLE
Question about Using Multiple Real Images as Input for Scene Generation in txt2room

### ISSUE THREAD

**Issue by Yuehongzhe** [lukasHoel/text2room#36]
Hey, love this work! I have a question regarding the scene generation process. Is it possible to use 2 or 3 real images as input and then generate additional synthetic images to create a complete 3D scene? If so, could you provide any guidance on how to achieve this?

Thanks!

**Comment by lukasHoel** [comment]
Hi, yes it should be possible. 

- If the images have no overlap, then you can predict their depth separately and merge them into the same world-space. You need to make sure that the predicted depth is roughly in the same range though. So maybe using a metric depth estimator for the first frames would make sense then. 

- If the images have overlap it depends on if you know their relative camera poses. If you know them, just treat them as if they were generated sequentially, i.e., select one image as the first, predict its depth and condition depth prediction for the other frames on the reprojected depth of the previous frames.  If you don't know their relative poses, but they have overlap, then you might want to look into multi-view depth estimation networks.
